version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      ignore:
        - "Cake.Core"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"